//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockEquipment
    {
        public int Id { get; set; }
        public Nullable<int> IdBlock { get; set; }
        public Nullable<int> IdEquip { get; set; }
        public string TypeEquip { get; set; }
        public string Title { get; set; }
    
        public virtual ProjectBlock ProjectBlock { get; set; }
        public virtual ProjectEquipment ProjectEquipment { get; set; }
    }
}
