//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockEquipment
    {
        public int Id { get; set; }
        public Nullable<int> IdBlock { get; set; }
        public Nullable<int> IdEquip { get; set; }
        public string TypeEquip { get; set; }
        public string Title { get; set; }
    
        public virtual ProjectBlock ProjectBlock { get; set; }
        public virtual ProjectEquipment ProjectEquipment { get; set; }
    }
}
