//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contactor()
        {
            this.ProjectEquipments = new HashSet<ProjectEquipment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdMotorPow { get; set; }
        public Nullable<int> IdMotorCur { get; set; }
        public Nullable<int> IdContCur { get; set; }
        public Nullable<int> IdHasRelay { get; set; }
        public Nullable<int> IdTypeCord { get; set; }
        public Nullable<int> IdTypeCoilCur { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
        public Nullable<int> IdSeria { get; set; }
        public string ContCatNumber { get; set; }
        public string RelayCabNumber { get; set; }
        public Nullable<int> IdCurrentBreaker { get; set; }
        public string ReloadCurValue { get; set; }
        public Nullable<int> IdIcu { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual NumericParam NumericParam { get; set; }
        public virtual NumericParam NumericParam1 { get; set; }
        public virtual NumericParam NumericParam2 { get; set; }
        public virtual Seria Seria { get; set; }
        public virtual StringParam StringParam { get; set; }
        public virtual StringParam StringParam1 { get; set; }
        public virtual StringParam StringParam2 { get; set; }
        public virtual StringParam StringParam3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectEquipment> ProjectEquipments { get; set; }
    }
}
