//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentTransform
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurrentTransform()
        {
            this.ProjectEquipments = new HashSet<ProjectEquipment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
        public string TypeSize { get; set; }
        public string TransFactor { get; set; }
        public string MeasureClass { get; set; }
        public string Power { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectEquipment> ProjectEquipments { get; set; }
    }
}
