//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisTypeModel
    {
        public int Id { get; set; }
        public Nullable<int> IdDisModel { get; set; }
        public Nullable<int> IdDisType { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
    
        public virtual DisModel DisModel { get; set; }
        public virtual DisType DisType { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
