//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public Nullable<int> IdNumber { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public Nullable<int> IdManager { get; set; }
        public Nullable<int> IdImplementer { get; set; }
        public Nullable<int> IdEditor { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IdState { get; set; }
        public Nullable<int> IdStage { get; set; }
    
        public virtual ProjectNumber ProjectNumber { get; set; }
        public virtual ProjectState ProjectState { get; set; }
        public virtual ProjectStage ProjectStage { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
