//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public Nullable<int> IdNumber { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public Nullable<int> IdManager { get; set; }
        public Nullable<int> IdImplementer { get; set; }
        public Nullable<int> IdEditor { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IdState { get; set; }
        public Nullable<int> IdStage { get; set; }
    
        public virtual ProjectNumber ProjectNumber { get; set; }
        public virtual ProjectState ProjectState { get; set; }
        public virtual ProjectStage ProjectStage { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
