//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectEquipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectEquipment()
        {
            this.BlockEquipments = new HashSet<BlockEquipment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdProjectNumber { get; set; }
        public Nullable<int> IdCbr { get; set; }
        public Nullable<int> IdCont { get; set; }
        public Nullable<int> IdModulEq { get; set; }
        public Nullable<int> IdCtr { get; set; }
        public Nullable<bool> Analog { get; set; }
        public Nullable<int> IdNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockEquipment> BlockEquipments { get; set; }
        public virtual Contactor Contactor { get; set; }
        public virtual CurrentBreaker CurrentBreaker { get; set; }
        public virtual CurrentTransform CurrentTransform { get; set; }
        public virtual EquipNote EquipNote { get; set; }
        public virtual ModulEquip ModulEquip { get; set; }
        public virtual ProjectNumber ProjectNumber { get; set; }
    }
}
