//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectBlock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectBlock()
        {
            this.BlockEquipments = new HashSet<BlockEquipment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Functional { get; set; }
        public Nullable<int> IdBaseH { get; set; }
        public Nullable<int> IdBaseB { get; set; }
        public Nullable<int> IdVSize { get; set; }
        public Nullable<int> IdSchema { get; set; }
        public string Note { get; set; }
        public Nullable<int> IdProjectNumber { get; set; }
    
        public virtual BaseSize BaseSize { get; set; }
        public virtual BaseSize BaseSize1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockEquipment> BlockEquipments { get; set; }
        public virtual ProjectNumber ProjectNumber { get; set; }
        public virtual Schema Schema { get; set; }
        public virtual VSize VSize { get; set; }
    }
}
